<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Presistence\DataSeeding\Data\Brands.json" />
		<None Remove="Presistence\DataSeeding\Data\Types.json" />
		<None Remove="Presistence\DataSeeding\Data\Products.json" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Presistence\DataSeeding\Data\Brands.json" />
		<None Remove="Presistence\DataSeeding\Data\Types.json" />
		<None Remove="Presistence\DataSeeding\Data\Products.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Presistence\DataSeeding\Data\Brands.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<Content Include="Presistence\DataSeeding\Data\Types.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>

		<Content Include="Presistence\DataSeeding\Data\Products.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CloudinaryDotNet" Version="1.29.3" />
		<PackageReference Include="Mapster" Version="10.0.10" />
		<PackageReference Include="Mapster.DependencyInjection" Version="10.0.10" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.17" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.17">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.17" />

		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.17" />

		<PackageReference Include="StackExchange.Redis" Version="2.8.31" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ECommerce.Application\ECommerce.Application.csproj" />
	</ItemGroup>

</Project>